name: Hugo site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Build the site in the hugo/builder container
      run: docker run --rm -v ${{ github.workspace }}:/src -v ${{ github.workspace }}/docs:/target klakegg/hugo:0.66.0
